LukeMathWalker/cargo-chef

.github/workflows/audit-on-push.yml, .github/workflows/general.yml, .github/workflows/scheduled-audit.yml, Cargo.lock, Cargo.toml, src/main.rs, src/recipe.rs
=> Target flag

src/main.rs
=> Return non-zero error code on failure.

src/lib.rs, src/main.rs, src/recipe.rs
=> Feature flags

README.md, src/recipe.rs, src/skeleton.rs
=> Lemmy fixes

src/skeleton.rs, tests/skeletons.rs
This is documented in https://doc.rust-lang.org/cargo/reference/cargo-targets.html
=> Fall back to default target names; run build_minimum_project in tests

Cargo.lock, Cargo.toml, src/main.rs, src/recipe.rs, src/skeleton.rs, tests/skeletons.rs
- Upgrade `cargo-manifest` to get bug fix contributed by @NathanHowell
=> Various fixes

README.md
=> Add some comparison with the 'naive approach'

Cargo.lock, Cargo.toml
=> Handle snake_case elements in cargo's manifest.

src/skeleton.rs, tests/skeletons.rs
When there are auto binaries (binaries not listed in the Cargo.toml, but
found in the "src/bin" directory), the only way to pick those up is
using the call to `cargo_manifest::Manifest::complete_from_path`.
However, there is no guarantee made here to the order of the binaries
after this call. As a result, it's often the case that the ordering of
the binaries is not consistent.
The skeleton is derived from this manifest, and the resulting recipe
file will differ because the binaries are in a different order. This can
cause Docker images to rebuild because they see a different file. In
reality, the data is the same, but in a sightly different order.
This commit sorts the order of the binaries in the manifest structure
before the file is written to disk, working around this problem.
=> Fixed ordering of autobins.

src/skeleton.rs, tests/skeletons.rs
=> 26 config.toml

src/lib.rs, src/main.rs, src/recipe.rs
I'm not sure how to test this.
Fixes #21
=> pass through --manifest-path and --package

src/skeleton.rs
In the past, package.version is track in `recipe.json` which will trigger full
project rebuild if package.version is bumped. To fix this issue, this patch
replace package.version to a constant value, so it won't trigger full project
rebuild.
Fix issue #35
=> Ignore package.version to avoid unnecessary rebuild

Cargo.lock, Cargo.toml
=> Pin clap's version

src/skeleton.rs, tests/skeletons.rs
I noticed when testing that my recipe.json was being rebuilt when I updated my package version number
=> fix version masking

.github/workflows/docker.yml
=> Fix docker publishing

README.md
fixes: https://github.com/LukeMathWalker/cargo-chef/issues/122
=> Use muslrust:stable instead of rust-musl-builder

src/skeleton/mod.rs
=> Fix binary issue.

src/main.rs, src/recipe.rs, src/skeleton/mod.rs
Adds support for multiple `--target` flags on the command line (similar to how cargo now supports it)
=> Support multiple `--target` flags in one invocation

src/lib.rs, src/main.rs, src/recipe.rs
Allow passing in `--all-features` to cargo.
=> add all-features as a flag

README.md
Removed duplicate cargo in README
=> Removed duplicate cargo in README

src/skeleton/mod.rs
This patch deletes the `workspace.default-members` array in the skeleton derived from `Cargo.toml` if it exists.
Cargo errors out if `workspace.default-members` contains entries that don't exist in `workspace.members`. But `cargo chef prepare --bin` modifies `workspace.members` as part of its normal operation, leaving the other fields untouched.
`default-members` is an entirely end-user-facing setting that controls which workspace members are built when running `cargo {check, build, test}` (among others) at the workspace root without specifying a target package. It has no effect on `cargo chef cook`.
The before/after behavior is described below.
Create the following workspace:
```sh
$ cat Cargo.toml
[workspace]
members = ["foo", "bar"]
default-members = ["foo", "bar"]
resolver = "2"
``` …
=> remove default-members from recipe

Cargo.lock, Cargo.toml, tests/skeletons.rs
=> Update cargo-manifest to 0.18.1. Fixes crate-type for binaries

src/skeleton/mod.rs, tests/skeletons.rs
I saw there were some clippy warnings that failed on the latest commit on main :)
=> fix: clippy warnings
