src/lib.rs, src/main.rs, src/recipe.rs, src/skeleton.rs, tests/skeletons.rs
Hi there, big fan of this project 😄 thought I'd share a change that has helped me out - building multiple targets, which picks up `dev-dependencies`. Happy to discuss further!
1. Add some flags to `cargo chef cook`, which are passed directly to `cargo build`:
1. `--benches`
2. `--tests`
3. `--examples`
4. `--all-targets`
2. Add skeleton files for `tests` and `examples` in the same fashion as already happens for `benches`.
In the build-test-release cycle, building and testing rust code often shares some (but not all) cacheable dependencies. With this change you can pre-compile both your production and your test dependencies, speeding up both, like so:
```dockerfile
FROM rust AS menu-planner
WORKDIR /app
COPY . /app/
RUN ["cargo", "chef", "prepare"]
FROM rust AS kitchen
WORKDIR /app
COPY …
```
=> Add cargo build targets to pick up dev-dependencies

README.md
Many thanks for working on cargo chef!
I was trying to adapt the example for my own use case and ran into this issue. I don't think the cargo home directory is guaranteed to be `/usr/local/cargo` so using [$CARGO_HOME](https://doc.rust-lang.org/cargo/guide/cargo-home.html) should make the example more portable.
=> Use environment variable instead of hardcoded value of $CARGO_HOME in readme

Cargo.toml, tests/recipe.rs
Make receipe construction deterministic.
The actual fix is in the `cargo-manifest` crate https://github.com/LukeMathWalker/cargo-manifest/pull/5 (which needs to be merged before this will go green).
Here I have added what I hope to be a reasonably comprehensive regression test.
closes #36
=> make recipe construction deterministic

src/recipe.rs, src/skeleton.rs
Should fix #42.
Fixes a build of an example project https://github.com/strohel/cargo-chef-build-rs for me.
We only needed to remove the case 1. b). That makes sense, because fingerprints only check what is in `build/`, and run of the build script has a dependency on its build.
Note that there is special case, which currently builds, but is not fully cached: when there is a `build.rs` file on filesystem, but no mention of `build = "build.rs"` in Cargo.toml. This one is separate though. It's proper fix would be to extend `cargo-manifest` to also autodetect `build` property in its `Manifest::complete_from_abstract_filesystem()` method (in addition to bins, libs, ...).
=> cook: clean up also dummy build.rs artifacts

Cargo.lock, Cargo.toml, README.md, src/main.rs
This PR addresses #27 and #31 by introducing a warning and interactive prompt when stdout is detected as being a TTY.
This should avoid surprise and actual source files being overwritten by the skeleton when running `cook` outside of container builds
=> Warning about file overwrite when stdout is a TTY

.github/workflows/docker.yml, docker/Dockerfile, docker/README.md
Currently uses just the "latest" tag of the upstream rust base image, but the
approach is extensible to many such tags.
Requires following GitHub repository secrets to be defined:
DOCKERHUB_USERNAME - username on https://hub.docker.com/
DOCKERHUB_TOKEN - token from Docker Hub for DOCKERHUB_USERNAME used to push images.
The job is scheduled to run every night, exiting early if current images are
up-to-date.
Seems to work fine:
- built image: https://hub.docker.com/r/strohel/cargo-chef
- GitHub job that built the image: https://github.com/strohel/cargo-chef/runs/1735587797
- GitHub job that was no-op because versions were up-to-date: https://github.com/strohel/cargo-chef/runs/1735685360
Fixes #41.
=> Add docker GitHub Actions workflow to build docker images 

src/skeleton.rs
> Thanks for awesome work! 🥳
`main` function should be defined if harness is disabled as mentioned in [document](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-harness-field).
I think [cucumber-rust](https://github.com/bbqsrc/cucumber-rust/blob/main/Cargo.toml#L43-L45) is a good sample for this issue:
```sh
error[E0601]: `main` function not found in crate `cucumber_builder`
|
= note: consider adding a `main` function to `tests/cucumber_builder.rs`
```
- Add dummy main function if test harness is disabled
=> Add dummy main function if test harness is disabled

src/skeleton.rs
* For recent versions of rust, compilation may create directories which match
the "/**/lib{}*" glob, so test the file type and remove these as well.
=> Remove artifact directories for libraries/build scripts from the current workspace

src/skeleton.rs
Issue #142 on toml-rs is already solved and is no longer the reason to parse to toml `Value`. 
The reason why this is needed is to sort the manifest.
=> Remove old incorrect commit

src/main.rs, src/recipe.rs
I would like to cook a whole workspace, but would prefer not to specify each member via `--package` manually.
This PR introduces the corresponding `--workspace` argument (superseding #28).
What do you think?
=> Add support for --workspace

src/main.rs, src/recipe.rs
to support building with vendored and patched dependencies. 
I typically run my build with
```
cargo build --offline -p <specific package name>
```
I tried translating my existing Dockerfile to use cargo chef,
but I was running into compilation errors where it wasn't
picking up the patched dependencies.
I commented out the portion of my Dockerfile
that ran `cook` and instead ran the above command.
This indeed works. So, I've added this option to the
necessary structs and where the `cargo` command is built.
=> Add `--offline` option

.github/workflows/docker.yml, Cargo.lock, Cargo.toml, docker/Dockerfile
Pulls current Rust docker image tags from [the official GitHub repo](https://github.com/docker-library/official-images/blob/master/library/rust).
Image tag format looks like this: `{cargo chef version}-rust-{dockerhub rust image tag}`. 
For non-alpha/beta versions of cargo-chef there's also a `latest-rust-{dockerhub rust image tag}` equivalent tag pushed, and a `latest` tag like before (which uses `rust:latest`).
E.g. for a non-alpha/beta version some tags pushed might be:
- `latest`
- `0.1.22-rust-1`
- `latest-rust-1`
- `latest-rust-1.52-buster`
- `0.1.22-rust-1.52.1-alpine3.12`
- `latest-rust-1.52.1-alpine3.12`
- etc...
For alpha/beta versions:
- `0.1.22-alpha.1-rust-1`
- `0.1.22-alpha.1-rust-1.52.1-alpine3.12`
- etc...
I set up a DockerHub repo while testing my changes. So examples of …
=> Build one Docker image per Rust version and tag with cargo-chef version number

src/main.rs, src/recipe.rs
I'm working on a CI setup where I want to be able to run both `cargo clippy` and `cargo build`. Without the `--check` flag, we need to rebuild the dependencies for checking each time. With this addition, `cargo clippy` is able to leverage the cache.
Thanks for the wonderful tool, it's really sped up our CI!
=> Add a --check flag

README.md
Since cargo-chef is intended for automated setups, it's better for reproducibility to use the binary's lock file during installation.
There's a relevant comment about `--locked` in `cargo install` docs: https://doc.rust-lang.org/cargo/commands/cargo-install.html
=> Suggest using --locked in README

Cargo.lock, Cargo.toml, src/main.rs, src/recipe.rs, src/skeleton.rs, tests/skeletons.rs
This adds support for using `cargo-chef` with `#[no_std]` crates.
When specifying `--no-std`, an appropriate `#[no_std]` template will be used for generating the skeleton.
On `proc-macro` crates and build scripts, this will be ignored. This allows `#[no_std]` workspaces to be built using `--workspaces`, even when they include `proc-macro` crates. When building workspaces which mix `std` and `#[no_std]` crates, `--no-std` has to be provided on a per crate basis, as there is no easy way to determine the `std`-ness of a crate, as far as I know.
What do you think?
=> Add flag for cooking #[no_std] crates

src/skeleton.rs, src/skeleton/mod.rs, src/skeleton/read.rs, src/skeleton/version_masking.rs, tests/skeletons.rs
Ensures that our recipe file is unchanged regardless of the order we read manifests from the filesystem.
We use the occasion to refactor the code in `Skeleton::derive`.
=> Reproducible order

README.md
The alpine build instructions in the readme will fail if copied because some arguments were being passed at the wrong time. This change makes it work
=> fix alpine instructions

src/skeleton/mod.rs
`cargo chef cook` will remove dummy compiled artifacts based off a couple of globs. The glob to remove library artifacts; however, can be a bit too eager and can match other libraries that are prefixed by the name of the desired library. Specifically this was noticed when the compiled artifacts of `libc` were getting removed while trying to remove the artifacts for a library simply named `lib`.
I believe the new globs should cover the patterns we want since library names are limited to just alphanumeric characters, `_`, and `-` with the hypen getting normalized to an underscore, so the new globs will match entries like
```text
liblib-<hash>.rlib
liblib-<hash>.rmeta
liblib.rlib
liblib.d
```
while not matching
```text
liblibc-<hash>.rlib
liblibc-<hash>.rmeta
```
=> Slightly more precise library artifact cleanup

.github/workflows/docker.yml
I had to modify the workflow because Docker does not yet support multi-platform images locally. We can't store the image and then push it if there are multiple platforms. I push it directly to DockerHub with several tags.
=> Fix #95 build docker images for arm64

README.md
1.53.0 doesn't support edition 2021, which new rust projects will default into:
```
`unknown variant `2021`, expected `2015` or `2018` for key `package.edition` at line 33 column 1`
```
=> Update README.md to use rust 1.56.0 not 1.53.0

Cargo.lock, Cargo.toml, src/main.rs
Nothing too exciting, just updates clap to the most recent version.
This change is actually because I noticed a slight inconsistency where `cargo` would accept `--features=` as default features while `cargo-chef` rejected it as missing a value. Looking into this further, I noticed that `clap` changed this behavior to match `cargo` in one of the more recent releases, so this PR fixes this minor CLI inconsistency
=> Update clap from v3.0 beta 2 to v3.1

.github/workflows/publish_binaries.yml
This adds publishing Linux musl based binaries to the releases. The changes are mostly a blend of the current implementation and [`cargo-hack`'s upload-assets job](https://github.com/taiki-e/cargo-hack/blob/main/.github/workflows/release.yml#L47-L82)
This is useful for when you need a musl build and the pre-build images don't quite cut it like building an alpine image with a nightly toolchain for instance
=> Publish linux musl binaries on release too

src/skeleton/mod.rs, src/skeleton/read.rs, tests/skeletons.rs
This is a quick stab at addressing https://github.com/LukeMathWalker/cargo-chef/issues/74.
There are two design questions: 
1. whether we filter these vendored `Cargo.toml` files from our list of manifests, or include them in the skeleton and then filter them out when we are `cooking`, and
2. How much do we want to hardcode to `cargo vendor`'s behavior.
Regarding 1., I prefer to filter these vendored files from our list of manifests. This makes testing easier (than having to render the recipe then checking directory outputs), keeps the manifests in the skeleton we serialize focused on what which projects we need to skelefy, and is robust against vendored files changing: if a vendored file changes the Docker sha of the step will change so it doesn't matter that the recipe.json file doesn't …
=> Ptw/issue 74 Do not skelefy vendored directory

src/main.rs, src/recipe.rs, src/skeleton/mod.rs
Fixes #109. This PR adds support for [profile flag](https://doc.rust-lang.org/cargo/reference/profiles.html), mimicking the same interface of `cargo build`
=> Add support for --profile flag

README.md, src/main.rs, src/recipe.rs
=> Automatically detect which Rust toolchain should be used

docker/Dockerfile
This error seems to have been introduced by the environment variable added in https://github.com/LukeMathWalker/cargo-chef/commit/f57e866a546a1cbddb08091381cf09aa50b65aaf.
Perhaps we can wait with extra speed until sparse index is in stable..?
=> ci: Fix failing builds

src/main.rs, src/recipe.rs, src/skeleton/mod.rs, tests/recipe.rs, tests/skeletons.rs
If specified, and if the top-level cargo.toml
has a members list, replace the list with
only the specified member. 
This is an attempt to address https://github.com/LukeMathWalker/cargo-chef/issues/125. 
If you have feedback on naming or code structure (I feel a little weird placing this function in `mod.rs`),
please let me know! I am happy to make those changes.
I have verified that this works for https://github.com/prestontw/cargo-chef-workspace-experiment
=> Add optional member flag to `prepare`

src/skeleton/version_masking.rs
Cargo chef currently does not support local [platform specific dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies)
During the prepare stage, it does not update the version of a local dependency like
```toml
[target.'cfg(windows)'.dependencies]
local-windows-package = {path = "./path/to/local", version = "0.1.3" }
```
To
```toml
[target.'cfg(windows)'.dependencies]
local-windows-package = {path = "./path/to/local", version = "0.0.1" }
```
But all local dependencies are set to version `0.0.1`, which means there is a version mismatch and `cargo chef cook` fails with a message like in https://github.com/LukeMathWalker/cargo-chef/issues/93
This PR fixes this behavior by adhering directly to all of the possible ways to specify …
=> Add support for platform specific dependencies

src/main.rs, src/recipe.rs
Pass through the `--timings` flag to `cargo` to be able to diagnose build times of dependencies.
=> feat: Add --timings argument

README.md
Readme refers to an old version of Rust. [Rust image](https://hub.docker.com/_/rust) already has `1` tag that refers to the latest stable version of 1.* for Rust or [cargo-chef image](https://hub.docker.com/r/lukemathwalker/cargo-chef/) already has `latest-rust-1` tag that refers to the same.
Some dependencies might require latest stable to work. In #160, `clap` 4.15.0 was a dependency, which was only available on the latest version of Rust. So, the build failed due to readme containing an old version of Rust.
Thus, it is sensible to change these lines in readme in order to refer to the latest stable version of Rust.
=> Fix Docker Tag in Readme

src/main.rs, src/recipe.rs
Adds support for [`cargo-zigbuild`](https://github.com/messense/cargo-zigbuild). This allows for better UX surrounding cross-platform compilation.
Users still need to install cargo-zigbuild manually and also install the Zig toolchain, though. I suppose it could be installed by chef too, but I'm not sure if that's the expected/desired behaviour.
Related:
- https://github.com/LukeMathWalker/cargo-chef/issues/135
=> Add support for `cargo-zigbuild`

src/lib.rs, src/main.rs, src/recipe.rs
Basically like https://github.com/LukeMathWalker/cargo-chef/pull/72, except for `clippy`.
Also extended a bit the config to allow better configuration of commands (e.g. for https://github.com/LukeMathWalker/cargo-chef/pull/158)
=> Extend to enable using for clippy

src/skeleton/version_masking.rs, tests/skeletons.rs
This PR applies version masking to local workspace dependencies. I ran into this when starting to implement workspace inheritance at shuttle: https://github.com/shuttle-hq/shuttle/pull/506. I tested it out by cloning my branch of cargo-chef in our Containerfile, and that caused the builds to succeed. 
This is my first PR to cargo-chef, so please let me know if I've misunderstood anything. :smile:  
Closes #167 
=> feat: mask workspace local dependencies

src/skeleton/mod.rs
Fixes #177 
Changes:
- Support `--target=target-name.json` to be passed to `cargo chef`, by fixing the target location that is used during dummy cleanup in this case.
=> Support for custom target files

docker/Dockerfile
Fixes #185
Remove environment variable CARGO_NET_GIT_FETCH_WITH_CLI=true. [Gets rid of](https://github.com/jacobsvante/cargo-chef/actions/runs/4135633866/jobs/7148369885) the `could not find cargo-chef in registry crates-io with version =X.X.X` error message that all alpine and some debian docker image builds end up with.
I think this optimization will soon be completely unnecessary anyway, considering that [sparse-registry will be stabilized in the next rust release](https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html).
(Fun side note is that this is exactly the same PR I did [half a year ago](https://github.com/LukeMathWalker/cargo-chef/pull/144).)
=> ci: Fix failing builds (again)

src/main.rs, src/recipe.rs
Similar to https://github.com/rust-lang/cargo/issues/1528, support passing multiple `package` arguments.
=> feat: support passing multiple `--package` arguments

tests/skeletons.rs
This PR adds a simple builder struct to define Cargo workspace directories in a more declarative way. I found a few bugs in the tests, but didn't fix them in this PR to keep original functionality (after this refactor, I'll send another PR with `cargo metadata`, which will fix the tests).
=> Add Cargo workspace builder to skeleton tests

.github/workflows/publish_binaries.yml
Fixes #188
`ubuntu-latest` recently changed to be 22.04, from 20.04. This broke binaries that were being built being run in older distros (e.g., Debian stable, as is the default for the `rust` docker image). This fixes that by building the binaries against the older glibc.
=> Build linux-gnu binaries on ubuntu 20.04

Cargo.lock, Cargo.toml, src/skeleton/mod.rs, src/skeleton/read.rs, tests/skeletons.rs
Fixes: https://github.com/LukeMathWalker/cargo-chef/issues/152
This PR adds basic usage of `cargo metadata`, which is not yet used to extract targets, but currently only to find workspace packages. This, adds built-in support for:
1) Ignoring vendored dependencies
2) Ignoring packages that are not part of the root workspace
3) Workspaces with packages specified using glob paths
4) Possibly also some other issues.
=> Use `cargo metadata` to find workspace manifests

tests/recipe.rs, tests/skeletons.rs
A few tests started failing on OSX after https://github.com/LukeMathWalker/cargo-chef/commit/3a1236c980244ebe9799956c16c732a511bde6d3
> ---- version stdout ----
> thread 'version' panicked at 'called `Result::unwrap()` on an `Err` value: failed to create directory `/var/folders/yh/kzjp2v3s02v2g69v0cm8f4x40000gn/T/.tmpEnxbkt/../../../../../../private/var/folders/yh/kzjp2v3s02v2g69v0cm8f4x40000gn/T/.tmpeW4tEa`
OSX symlinks '/var' to '/private/var' - the paths created by TempDir start with '/var' but when read back via `cargo metadata` start with '/private/var'. 
This PR canonicalizes to ensure relative directory calculations work as expected on OSX.
=> Fix tests on OSX after introduction of "cargo metadata"

src/skeleton/mod.rs, tests/skeletons.rs
…since the binary target might depend on them via a path dependency.
We could be more surgical and keep exclusively the ones that are in the binary's transitive dependency closure, but we'll leave that for a future PR.
=> We should keep all manifests, even if they are not mentioned in the list of workspace members

src/skeleton/version_masking.rs, tests/skeletons.rs
Our current implementation is a bit naive and doesn't account for package renames of local dependencies.
This PR fixes it.
=> Masking should take into account package renames.

src/skeleton/mod.rs
This change restores the old behaviour of ``cargo chef prepare`` which would finish quickly and not need Git credentials for private repos.
=> fix: Run `cargo metadata` with no-deps flag

src/skeleton/mod.rs, src/skeleton/read.rs, src/skeleton/target.rs, tests/skeletons.rs
This should help generate the correct entrypoint file paths, instead of guessing them.
=> Use `cargo metadata` to resolve targets

.github/workflows/audit-on-push.yml, .github/workflows/docker.yml, .github/workflows/general.yml, .github/workflows/publish_binaries.yml, .github/workflows/scheduled-audit.yml
**Issue #, if available**
Try to remove noisy warnings inside github actions
**Description of changes**
Principally by bumping to new tag version (e.g.
`action/checkout`). But for unmaintained actions the swap
with a fork or something similar, is the only solution:
* [`action-rs/toolchain`](https://github.com/actions-rs/toolchain/issues/216) -> [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain)
* [`action-rs/audit-check`](https://github.com/actions-rs/audit-check/issues/227) -> [`rustsec/audit-check`](https://github.com/rustsec/audit-check)
Two consequences of using `dtolnay/rust-toolchain` are:
* no more needed `CARGO_TERM_COLOR=always` already set by
the action
* use directly cargo commands in run steps
I also change …
=> Solve CI warnings replacing outdated actions

.github/dependabot.yml, .github/workflows/audit-on-push.yml, .github/workflows/docker.yml, .github/workflows/general.yml, .github/workflows/publish_binaries.yml, .github/workflows/scheduled-audit.yml
**Related:** #221
**Description of changes:**
Explicitly set permissions required inside github actions
For **dependabot** what you'd prefer for `schedule` interval?
And for the preference you expressed:
> raise PRs unless there is a semver-breaking version bump
I think the closest behavior can be ignoring semver patch release for all actions,
instead minor, major usually can contain some breaking changes. Is it ok?
*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*
=> Best practies for github actions: permissions and dependabot

src/main.rs, src/recipe.rs
This introduces the frozen and locked behaviors to cargo chef. 
See: https://doc.rust-lang.org/cargo/commands/cargo-build.html#manifest-options
=> feat: add frozen and locked

src/skeleton/mod.rs, src/skeleton/read.rs, tests/skeletons.rs
*Issue #, if available:* #231
*Description of changes:* Added rust-toolchain to the skeleton. I'm differentiating between `rust-toolchain` and `rust-toolchain.toml` because the former seems to be handled differently, e.g. can contain just the channel and not be actually toml, but it is kept only for backwards compatibility reasons. It is however preferred if both are present so I could just read either and otuput it as `rust-toolchain`?
=> Add rust-toolchain.toml to skeleton

Cargo.lock, Cargo.toml, src/main.rs
Replaces `atty` crate with `std::io::IsTerminal` trait.
=> chore: Replace atty crate with std::io::IsTerminal

src/skeleton/mod.rs, src/skeleton/read.rs, tests/skeletons.rs
Closes: #232 
The current code assumes that when running `prepare` with `--bin`, that we can remove all members and just add one member that is equal to whatever we passed in `--bin`.
The problem with that is that if your packages aren't in the exact same root directory, then this will result in a recipe file that breaks once you try calling `cook` on it.
To fix this, this PR instead sets the sole member to the _path_ of the package, which (I think) can be found using in `cargo_metadata::Metadata`, grabbing the manifest path, and setting it to be relative to the workspace root + removing `Cargo.toml` from the path. I chose to do it this way rather than just matching + grabbing whatever's in the `members` array as I don't think that would …
=> use the manifest path instead of just the member name when using `prepare --bin`

src/main.rs
Updates `clap` 4 deprecated APIs.
=> chore: resolve clap 4 deprecated api

src/skeleton/mod.rs
This should close #276.
These could also be added to the `OptimisationProfile` enum but that would be a breaking change.
=> Improve support for bench/dev/test profiles

.github/workflows/docker.yml
I am not sure what had happened here...
In this commit: https://github.com/LukeMathWalker/cargo-chef/commit/9e017baaa49ab80bdf3cdaf2e54978322df48fa7, the is_duplicated step appears to be broken.
You can observe it for example here: https://github.com/LukeMathWalker/cargo-chef/actions/runs/15361613141/job/43229423187
```
Run CHEF_IMAGE=$DOCKER_REPO:$CHEF_IMAGE_TAG
CHEF_IMAGE=$DOCKER_REPO:$CHEF_IMAGE_TAG
CHEF_IMAGE_TAG=$CHEF_PACKAGE_VERSION-rust-$RUST_IMAGE_TAG
if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $CHEF_IMAGE >/dev/null; then
echo "There is already a pushed image with ${CHEF_IMAGE_TAG} as tag. Skipping."
echo "result=true" >> "$GITHUB_OUTPUT"
else
echo "result=false" >> "$GITHUB_OUTPUT"
fi
shell: /usr/bin/bash -e {0}
env:
RUST_IMAGE_TAG: latest
DOCKERHUB_USERNAME: *** …
```
=> fix: Assign `CHEF_IMAGE_TAG` before it is used in `CHEF_IMAGE` env

.github/workflows/publish_binaries.yml
=> ci: add release for aarch64-unknown-linux-gnu
